package enums;

public enum ECommand {
    KANEAD_DOUGH, PUT_PICKLES, PUT_MUSHROOMS, PUT_BASIL, PUT_TOMATOES, PUT_SAUSAGE, PUT_OLIVES, PUT_CORN, PUT_CHICKEN,PUT_CHEESE ,PUT_PINEAPPLE, PUT_SAUCE, TO_BAKE
}
